DROP TABLE APPS.XX_GRN_PROCESS_LOGS CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_GRN_PROCESS_LOGS
(
  SHIPMENT_HEADER_ID  VARCHAR2(30 BYTE),
  LOG_TEXT            VARCHAR2(400 BYTE),
  CREATION_DATE       DATE
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
