DROP TABLE APPS.XX_RECEIPT_APPROVER_HISTORY CASCADE CONSTRAINTS;

CREATE TABLE APPS.XX_RECEIPT_APPROVER_HISTORY
(
  SHIPMENT_HEADER_ID  NUMBER,
  SHIPMENT_LINE_ID    NUMBER,
  APPROVER_ID         NUMBER,
  HISTORY_ID          NUMBER
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
